services:
  # -------------------------
  # Application Database
  # -------------------------
  mysql:
    image: mysql:8.0
    container_name: sobitas-mysql
    restart: unless-stopped
    env_file: 
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/protein_db.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - sobitas-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u${MYSQL_USER}", "-p${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10

  # -------------------------
  # PHP-FPM (Laravel)
  # -------------------------
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sobitas-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    networks:
      - sobitas-net
    expose:
      - "9000"
    depends_on:
      - mysql
    healthcheck:
      test: ["CMD-SHELL", "php -v >/dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
    # Remove host mount to preserve built vendor folder
    # volumes:
    #   - ./backend:/var/www/html:delegated

  # -------------------------
  # Nginx for Laravel
  # -------------------------
  laravel-nginx:
    image: nginx:stable
    container_name: sobitas-laravel-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html:ro
      - ./nginx/laravel.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - sobitas-net
    depends_on:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "nginx -t >/dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

  # -------------------------
  # Angular Frontend
  # -------------------------
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sobitas-frontend
    restart: unless-stopped
    ports:
      - "4200:8080"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./nginx-frontend/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - sobitas-net
    depends_on:
      - backend

  # -------------------------
  # Nginx Proxy Manager
  # -------------------------
  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: sobitas-npm
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    environment:
      DB_MYSQL_HOST: npm-db
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: npm
      DB_MYSQL_PASSWORD: npm
      DB_MYSQL_NAME: npm
    volumes:
      - npm-data:/data
      - npm-letsencrypt:/etc/letsencrypt
      - ./letsencrypt/credentials:/etc/letsencrypt/credentials
    networks:
      - sobitas-net
    depends_on:
      - npm-db
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:81 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

  # -------------------------
  # NPM's MySQL
  # -------------------------
  npm-db:
    image: mysql:8.0
    container_name: sobitas-npm-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: npmroot
      MYSQL_DATABASE: npm
      MYSQL_USER: npm
      MYSQL_PASSWORD: npm
    volumes:
      - npm-db-data:/var/lib/mysql
    networks:
      - sobitas-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "npm", "-p npm"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-data:
  npm-data:
  npm-letsencrypt:
  npm-db-data:

networks:
  sobitas-net:
    driver: bridge

